# Generated by Django 5.1.6 on 2025-02-18 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='codigo',
            field=models.CharField(default='', editable=False, max_length=8, unique=True),
        ),
    ]
