# Generated by Django 5.1.6 on 2025-02-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_aluno_matricula_alter_turma_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='matricula',
            field=models.CharField(default='TEMP1234', editable=False, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='professor',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='professor',
            name='turmas',
            field=models.ManyToManyField(blank=True, to='core.turma'),
        ),
    ]
