# Generated by Django 5.1.6 on 2025-02-19 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_professor_matricula_alter_professor_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presenca',
            name='domingo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presenca',
            name='turma',
            field=models.ForeignKey(default=1234, on_delete=django.db.models.deletion.CASCADE, related_name='chamadas', to='core.turma'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='presenca',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='presenca',
            unique_together={('aluno', 'data')},
        ),
    ]
