# Generated by Django 5.1.6 on 2025-02-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_presenca_domingo_presenca_turma_alter_presenca_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='turmas',
        ),
        migrations.AddField(
            model_name='turma',
            name='professores',
            field=models.ManyToManyField(blank=True, related_name='turmas', to='core.professor'),
        ),
    ]
