# Generated by Django 5.1.6 on 2025-02-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_professor_turmas_turma_professores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='professores',
        ),
        migrations.AddField(
            model_name='professor',
            name='turmas',
            field=models.ManyToManyField(blank=True, to='core.turma'),
        ),
    ]
